direction: right

host1: Host 1 {
  ls: LocalStack {
    icon: ./images-src/assets/localstack.svg
    shape: image
  }
}

host2: Host 2 {
  script: Your code {
    icon: ./images-src/assets/script.svg
    shape: image
  }
}

host1.ls <- host2.script: <endpoint> {
  style: {
    font-size: 24
  }
}
