direction: right

host1: Host 1 {
  ls: LocalStack {
    icon: https://avatars.githubusercontent.com/u/28732122?s=200&v=4
    shape: image
  }

  docdb: Resource {
    icon: ./images-src/assets/documentdb.svg
    shape: image
  }
}

host2: Host 2 {
  script: Your code {
    icon: https://upload.wikimedia.org/wikipedia/commons/8/82/Text-x-python.svg
    shape: image
  }
}

host1.docdb <- host2.script: {
  style: {
    font-size: 24
  }
}
