direction: right

host: Host {
  docker: Docker Network {
    ls: LocalStack {
      icon: ./images-src/assets/localstack.svg
      shape: image
    }

    container: "" {
      icon: ./images-src/assets/ecs.svg
      shape: image
    }
  }
}

host.docker.ls <- host.docker.container: <endpoint> {
  style: {
    font-size: 24
  }
}
