direction: right

host: Host {
  docker: Docker Network {
    ls: LocalStack {
      icon: ./images-src/assets/localstack.svg
      shape: image
    }

    lambda: "" {
      icon: ./images-src/assets/lambda.svg
      shape: image
    }
  }
}

host.docker.ls <- host.docker.lambda: AWS SDK {
  style: {
    font-size: 24
  }
}
