direction: right

host: Host {
  docker: Docker Network {
    ls: LocalStack {
      icon: ./images-src/assets/localstack.svg
      shape: image
    }

    script: Your code {
      icon: ./images-src/assets/docker.svg
      shape: image
    }
  }
}

host.docker.ls <- host.docker.script: <endpoint> {
  style: {
    font-size: 24
  }
}
