direction: right

host: Host {
  docker: Docker Network {
    ls: LocalStack {
      icon: ./images-src/assets/localstack.svg
      shape: image
    }

    docdb: Resource {
      icon: ./images-src/assets/documentdb.svg
      shape: image
    }
  }

  script: Your code {
    icon: ./images-src/assets/script.svg
    shape: image
  }
}

host.docker.docdb <- host.script
