direction: right

ls: LocalStack {
  icon: ./images-src/assets/localstack.svg
  shape: image
}

docdb: Resource {
  icon: ./images-src/assets/documentdb.svg
  shape: image
}

script: Your code {
  icon: ./images-src/assets/script.svg
  shape: image
}

docdb <- script: {
  style: {
    font-size: 24
  }
}
