direction: right

ls: LocalStack {
  icon: ./images-src/assets/localstack.svg
  shape: image
}

script: Your code {
  icon: ./images-src/assets/script.svg
  shape: image
}

ls <- script: <endpoint> {
  style: {
    font-size: 24
  }
}
