blank_issues_enabled: false
contact_links:
  - name: 📖 LocalStack Documentation
    url: https://docs.localstack.cloud/overview/ 
    about: Use our docs to answer your questions!
  - name: 💬 LocalStack Community Support (Slack)
    url: https://localstack.cloud/slack 
    about: Please ask and answer questions in our Slack.