globs:
  - 'content/**/*.md'
ignores:
  - 'node_modules'
  # Weird behavior with markdownlint; TODO: Fix
  - 'content/en/tutorials/cloud-pods-collaborative-debugging/*'
  - 'content/en/user-guide/integrations/terraform/*'
  - 'content/en/user-guide/aws/events/*'
customRules:
  - markdownlint-rule-max-one-sentence-per-line
config:
  MD029: false # Ordered list item prefix
  MD046: false # Code block style
  MD025: false # Single H1
  MD001: false # Header levels increment by one
  MD024: false # Multiple headers with the same content
  MD055: false # Inconsistent leading and trailing pipe characters
  MD056: false # Inconsistent Table column count
  MD036: false # Emphasis used instead of a header
  MD003: false # Header style
  MD033: false # Inline HTML
  MD013: false # Line length
  MD034: false # Bare URL used
  MD032: false # Lists should be surrounded by blank lines
  MD018: false # No space after hash on atx style header
  MD022: false # Headers should be surrounded by blank lines
