globs:
  - 'content/**/*.md'
ignores:
  - 'node_modules'
# customRules:
#   - markdownlint-rule-max-one-sentence-per-line
config:
  MD029: false
  MD046: false
  MD025: false
  MD001: false
  MD024: false
  MD055: false
  MD056: false
  MD036: false
  MD003: false
  MD033: false
  MD013: false
  MD034: false
  MD032: false
  blanks-around-headings:
    lines_above: 0
    lines_below: 1
