name: 📑 Docs
description: Propose changes and improvements to LocalStack Docs.
labels: "📑 docs"
title: "[📑 Docs]: "
assignees: quetzalliwrites, HarshCasper
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to LocalStack Docs! We appreciate your feedback, ideas, and contributions. 
  
  - type: textarea
    id: reason-context
    attributes:
      label: What docs changes are you proposing?
      description: Why do the docs need this improvement? What is the motivation for this change?
      placeholder: "I would like to contribute to LocalStack Docs 📑 by..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/localstack/docs?tab=coc-ov-file#readme)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true