name: Documentation linter

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'

jobs:
  check-all-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Broken link checker
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.github/workflows/markdown.links.config.json'
          folder-path: 'content/en/'
          check-modified-files-only: 'yes'
          file-extension: '.md'
          base-branch: 'main'
