name: Documentation linter

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'

jobs:
  check-all-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Broken link checker
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          # The following config contains this workaround: https://github.com/tcort/markdown-link-check/issues/201#issuecomment-1110242146
          # as otherwise links to docs.github.com are considered dead.
          # When the issue gets resolved, it might be fine to remove the workaround.
          config-file: '.github/workflows/markdown.links.config.json'
          folder-path: 'content/en/'
          check-modified-files-only: 'yes'
          file-extension: '.md'
          base-branch: 'main'
